- hosts: "{{groups.compute[0]}}"
  gather_facts: no
  connection: local
  vars:
    installer_url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/qvfM-wPedgAJZNUA2acjVpqmAmqzghHdTlLWsGtdc6cArD856vxBaBNDdJlvLYDF/n/hpc/b/HPC_APPS/o/STAR-CCM+15.04.008_01_linux-x86_64-2.12_gnu7.1.zip"
    installer:
      - { name: STAR-CCM+15.04.008_01_linux-x86_64-2.12_gnu7.1 , url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/qvfM-wPedgAJZNUA2acjVpqmAmqzghHdTlLWsGtdc6cArD856vxBaBNDdJlvLYDF/n/hpc/b/HPC_APPS/o/STAR-CCM+15.04.008_01_linux-x86_64-2.12_gnu7.1.zip"}
    models:
      - { name: lemans_poly_17m.amg, url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/Mw6IP3j_ABLQEqr22wDkHjMGZzLERxuZyvuQ4Q5IsHE/n/hpc/b/starccm_benchmarks/o/lemans_poly_17m.amg.sim.tgz" }
  tasks:
  - name: mkdir
    file:
      path: "{{vars.nfs_mount_path}}/install/starccm"
      state: directory
  - name: mkdir
    file:
      path: "{{vars.nfs_mount_path}}/installers/starccm"
      state: directory
  - name: Download installer
    unarchive:
      src: "{{item.url}}"
      dest: "{{vars.nfs_mount_path}}/installers/starccm"
      remote_src: yes
    with_items: "{{vars.installer}}"
  - name: Install StarCCM
    shell: "{{vars.nfs_mount_path}}/installers/starccm/{{item.name}}/{{item.name}}.sh -i silent -DINSTALLDIR={{vars.nfs_mount_path}}/install/starccm"
    poll: 0
    with_items: "{{vars.installer}}"
  - name: mkdir
    file:
      path: "{{vars.nfs_mount_path}}/work/starccm/{{item.name}}"
      state: directory
    with_items: "{{vars.models}}"
  - name: Download and unarchive model
    unarchive:
      src: "{{item.url}}"
      dest: "{{vars.nfs_mount_path}}/work/starccm/{{item.name}}"
      remote_src: yes
    with_items: "{{vars.models}}" 
  - name: move files
    copy:
      src: "{{vars.nfs_mount_path}}/work/starccm/{{item.name}}/lemans/data/case/"
      dest: "{{vars.nfs_mount_path}}/work/starccm/{{item.name}}/"
    with_items: "{{vars.models}}"
  - file:
      path: "{{vars.nfs_mount_path}}/work/starccm/{{item.name}}/lemans"
      state: absent
    with_items: "{{vars.models}}"
  - name: add machinefile
    command: sed 's/$/:36/' /etc/opt/oci-hpc/hostfile > "{{vars.nfs_mount_path}}/work/starccm/machinefile"
  - name: export INSTALLPATH # need to fix this for other models
    lineinfile:
      path: /home/opc/.bashrc
      line: "export INSTALLPATH={{vars.nfs_mount_path}}/install/starccm/15.04.008/STAR-CCM+15.04.008"
  - name: export MODELNAME # need to fix this for other models
    lineinfile:
      path: /home/opc/.bashrc
      line: "export MODELNAME={{vars.nfs_mount_path}}/work/starccm/lemans_poly_17m.amg/lemans_poly_17m.amg.sim"
  - name: export MACHINEFILE # need to fix this for other models
    lineinfile:
      path: /home/opc/.bashrc
      line: "export MACHINEFILE={{vars.nfs_mount_path}}/work/starccm/machinefile"
- hosts: compute
  become: true
  tasks:
  - name: install mysql
    yum:
      name: mysql
      state: latest
