- hosts: "{{groups.compute[0]}}"
  gather_facts: no
  connection: local
  tasks:
  - name: mkdir
    file:
      path: "{{vars.nfs_mount_path}}/OpenFOAM/install"
      state: directory
  - name: wget install intelmpi openfoam8
    get_url: 
      url: https://objectstorage.us-phoenix-1.oraclecloud.com/p/96Um0TDiq3Y9CuBknloaOwaAdq6yS9XQ4h4dK3mpE6c/n/hpc/b/HPC_APPS/o/OpenFOAM-8_GCC_IMPI2019.tar
      dest: "{{vars.nfs_mount_path}}/OpenFOAM/install/OpenFOAM-8_GCC_IMPI2019.tar"
  - name: untar intelmpi openfoam8
    unarchive:
      src: "{{vars.nfs_mount_path}}/OpenFOAM/install/OpenFOAM-8_GCC_IMPI2019.tar"
      dest: "{{vars.nfs_mount_path}}/OpenFOAM/install/"
  - name: mkdir
    file:
      path: "{{vars.nfs_mount_path}}/OpenFOAM/models"
      state: directory
  - name: wget motorbike model 
    get_url:
      url: https://objectstorage.us-phoenix-1.oraclecloud.com/p/tyE3Jo5JnlV0wS4ywoPJfyavXdXhmG4lRsAporCoOqg/n/hpc/b/HPC_BENCHMARKS/o/motorbike_RDMA.tgz
      dest: "{{vars.nfs_mount_path}}/OpenFOAM/models/motorbike_RDMA.tgz"
  - name: untar Openfoam motorbike 
    unarchive:
      src: "{{vars.nfs_mount_path}}/OpenFOAM/models/motorbike_RDMA.tgz"
      dest: "{{vars.nfs_mount_path}}/OpenFOAM/models/"
  - name: copy allrun script to models
    copy:
      src: ~/bench/intelmpiAllrun.sh
      dest: "{{vars.nfs_mount_path}}/OpenFOAM/models/intelmpiAllrun.sh"
  - name:  make allrun script executable
    command: chmod +x "{{vars.nfs_mount_path}}/OpenFOAM/models/intelmpiAllrun.sh"
- hosts: compute
  tasks:
  - name: add source line (intel)
    lineinfile:
      path: /home/opc/.bashrc
      line: "source /opt/intel/compilers_and_libraries_2019.4.243/linux/mpi/intel64/bin/mpivars.sh"
      create: yes
  - name: export MPI_ROOT (intel)
    lineinfile:
      path: /home/opc/.bashrc
      line: export MPI_ROOT=/opt/intel/compilers_and_libraries_2019.4.243/linux/mpi
      create: yes
  - name: add source openfoam8 bashrc
    lineinfile:
      path: /home/opc/.bashrc
      line: "source {{vars.nfs_mount_path}}/OpenFOAM/install/OpenFOAM-8/etc/bashrc"
  - name: add hostname to intel mpi hostfile
    lineinfile:
      path: "{{vars.nfs_mount_path}}/OpenFOAM/models/hostfile_intel"
      line: "{{ansible_host}}:36"
      create: yes
- hosts: compute
  become: true
  tasks:
  - name: install mysql
    yum:
      name: mysql
      state: latest
